# Site settings
author: David Gilbert
title: David's Awesome Coding Blog
header-img: img/home-bg.png
email: dagilbert333@gmail.com
copyright_name: David Gilbert
description: > # this means to ignore newlines until "baseurl:"
  Kick off your shoes and relax your feet!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dagilbert333

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
